In [1]:
import numpy as np 

In [2]:
a1= np.array([1,2,3,4,5])

In [3]:
a1

array([1, 2, 3, 4, 5])

In [4]:
a1.shape

(5,)

In [5]:
a2 = np.array([[1,2,3],
                [4,5,6]])

In [6]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a2.shape

(2, 3)

In [8]:
n2 = np.array([[1,2,3,4],[6,7,8,9],[10,15,17,18]])

In [9]:
n2

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 15, 17, 18]])

In [10]:
a3 = np.array([[[1,2,3],[4,5,6]],
[[9,10,11],[12,13,14]]])

In [11]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 9, 10, 11],
        [12, 13, 14]]])

In [12]:
a3.shape

(2, 2, 3)

In [13]:
np.array([[[1,2],[3,4],[11,12]],[[5,6],[7,8],[13,14]]])

array([[[ 1,  2],
        [ 3,  4],
        [11, 12]],

       [[ 5,  6],
        [ 7,  8],
        [13, 14]]])

In [14]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a2.ravel()

array([1, 2, 3, 4, 5, 6])

In [16]:
a3.ravel()

array([ 1,  2,  3,  4,  5,  6,  9, 10, 11, 12, 13, 14])

In [17]:
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [18]:
np.arange(10,158,17)

array([ 10,  27,  44,  61,  78,  95, 112, 129, 146])

In [19]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
np.arange(27).reshape(3,3,3,1)

array([[[[ 0],
         [ 1],
         [ 2]],

        [[ 3],
         [ 4],
         [ 5]],

        [[ 6],
         [ 7],
         [ 8]]],


       [[[ 9],
         [10],
         [11]],

        [[12],
         [13],
         [14]],

        [[15],
         [16],
         [17]]],


       [[[18],
         [19],
         [20]],

        [[21],
         [22],
         [23]],

        [[24],
         [25],
         [26]]]])

In [21]:

r =(np.random.random(12)*100).reshape(3,4)

In [22]:
np.random.randint(25,68,6)

array([45, 55, 34, 30, 55, 66])

In [23]:
r

array([[61.40082765, 50.19197898, 96.27833704, 13.35592445],
       [50.41477149, 50.95151815, 44.25637452,  8.1478835 ],
       [95.07070609, 65.80489938, 55.22042011, 30.73748633]])

In [24]:
np.round(r)

array([[61., 50., 96., 13.],
       [50., 51., 44.,  8.],
       [95., 66., 55., 31.]])

In [25]:
a1

array([1, 2, 3, 4, 5])

In [26]:
np.round(r,2)

array([[61.4 , 50.19, 96.28, 13.36],
       [50.41, 50.95, 44.26,  8.15],
       [95.07, 65.8 , 55.22, 30.74]])

In [27]:
np.ceil(r)

array([[62., 51., 97., 14.],
       [51., 51., 45.,  9.],
       [96., 66., 56., 31.]])

In [28]:
np.floor(r)

array([[61., 50., 96., 13.],
       [50., 50., 44.,  8.],
       [95., 65., 55., 30.]])

In [29]:
a = np.random.randint(1,100,9)
b = np.random.randint(1,100,24).reshape(6,4)
c = np.random.randint(1,100,27).reshape(3,3,3)

In [30]:
a

array([ 6, 21, 32, 40, 60, 41, 64, 49, 12])

In [31]:
np.sum(a)

325

In [32]:
np.prod(a)

1144520704

In [33]:
np.max(a)

64

In [34]:
np.min(a)

6

In [35]:
np.mean(a)

36.111111111111114

In [36]:
np.median(a)

40.0

In [37]:
b

array([[42,  8, 13, 33],
       [22, 77, 76, 54],
       [78, 56, 94, 74],
       [23,  6, 28, 87],
       [58, 33, 85, 15],
       [55, 29, 45, 62]])

In [38]:
np.sum(b)

1153

In [39]:
np.sum(b,axis=1) # 1->row

array([ 96, 229, 302, 144, 191, 191])

In [40]:
np.sum(b,axis=0) # 0 ->col

array([278, 209, 341, 325])

In [41]:
np.max(b)

94

In [42]:
np.max(b,axis=0)

array([78, 77, 94, 87])

In [43]:
a1

array([1, 2, 3, 4, 5])

In [44]:
np.prod(a1)

120

### INDEXING SLICING

In [45]:
a

array([ 6, 21, 32, 40, 60, 41, 64, 49, 12])

In [46]:
#78,57,4
a[2::3]

array([32, 41, 12])

In [47]:
a[4]

60

In [48]:
a[6]

64

In [49]:
#78,40,27
a[2:7:2]

array([32, 60, 64])

In [50]:
b

array([[42,  8, 13, 33],
       [22, 77, 76, 54],
       [78, 56, 94, 74],
       [23,  6, 28, 87],
       [58, 33, 85, 15],
       [55, 29, 45, 62]])

In [51]:
# 3,85,59,29
# 74,20,18,84
# 18,15,54,37
# 64,95,33,5
# 18,95,59,50
# 3,37,54,5
# 17,45,30,63
# 74,45,64,95,33,5
# 18,95,59,50,54,5


In [52]:
# 85, 37,64,95
b[1:3,::2]

array([[22, 76],
       [78, 94]])

In [53]:
# 74,64,33
b[::2,0]

array([42, 78, 58])

In [54]:
#54,29
b[3,::3]

array([23, 87])

In [55]:
# 3,37
b[1,1:3]

array([77, 76])

In [56]:
b[2]

array([78, 56, 94, 74])

In [57]:
# 84
b[5,3]

62

In [58]:
# 5

b[4,2]

85

In [59]:
b[2,2]

94

In [60]:
b[2][2]

94

In [61]:
a

array([ 6, 21, 32, 40, 60, 41, 64, 49, 12])

In [62]:
a.size

9

In [63]:
b

array([[42,  8, 13, 33],
       [22, 77, 76, 54],
       [78, 56, 94, 74],
       [23,  6, 28, 87],
       [58, 33, 85, 15],
       [55, 29, 45, 62]])

In [64]:
b.size

24

In [65]:
b.ndim

2

In [66]:
c.ndim

3

In [67]:
a.dtype

dtype('int32')

In [ ]:
a.astype('f')

array([ 6., 21., 32., 40., 60., 41., 64., 49., 12.], dtype=float32)

In [71]:
a.astype('str')

array(['6', '21', '32', '40', '60', '41', '64', '49', '12'], dtype='<U11')

In [72]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [74]:
np.zeros((2,3),'i')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [75]:
np.ones((2,3),'i')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [77]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
np.eye(5,5,0,'i')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

In [80]:
np.identity(5,'i')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

In [88]:
a = np.arange(5)
b = np.arange(5,10)

In [89]:
a

array([0, 1, 2, 3, 4])

In [90]:
b

array([5, 6, 7, 8, 9])

In [91]:
a+b

array([ 5,  7,  9, 11, 13])

In [92]:
a = np.arange(5)
b = np.arange(5,15).reshape(2,5)

In [93]:
a,b

(array([0, 1, 2, 3, 4]),
 array([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]))

In [94]:
a+b

array([[ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18]])

In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(1,4)

In [96]:
a,b

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([0, 1, 2, 3]))

In [97]:
a+b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [98]:
a = np.arange(3).reshape(1,3)
b=  np.arange(3,6).reshape(3,1)

In [99]:
a

array([[0, 1, 2]])

In [100]:
b

array([[3],
       [4],
       [5]])

In [101]:
a+b

array([[3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [102]:
a= np.arange(1)
b= np.arange(4).reshape(2,2)

In [103]:
a+b

array([[0, 1],
       [2, 3]])

In [104]:
b= np.arange(16).reshape(4,4)
a= np.arange(4).reshape(2,2)

In [105]:
a+b

ValueError: operands could not be broadcast together with shapes (2,2) (4,4) 

In [106]:

a= np.arange(4).reshape(1,4)
b= np.arange(5,10).reshape(5,1)

In [107]:
a+b

array([[ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12]])

In [109]:
b = np.random.randint(1,100,24).reshape(6,4)

In [111]:
b

array([[50, 54, 59,  9],
       [78, 59, 67, 65],
       [29, 13, 45,  9],
       [97, 82, 42, 68],
       [96, 87, 87, 85],
       [ 2, 27, 55, 92]])

In [114]:
b[[1,2],[1,2]] # fancy indexing or advanced indexing 

array([59, 45])

In [ ]:
#boolean indexing 

In [115]:
a = np.random.randint(1,100,25)

In [116]:
a

array([21, 87, 30,  6, 19, 80, 57, 94, 64, 67, 16, 89, 67, 70, 36, 56, 75,
       65, 10, 89,  6, 17,  8, 90, 98])

In [118]:
a[a>50]

array([87, 80, 57, 94, 64, 67, 89, 67, 70, 56, 75, 65, 89, 90, 98])

In [119]:
a[a%2==0]

array([30,  6, 80, 94, 64, 16, 70, 36, 56, 10,  6,  8, 90, 98])

In [120]:



c = np.random.randint(1,100,27).reshape(3,3,3)

In [121]:
c

array([[[58, 31, 63],
        [66, 94, 76],
        [46, 62, 22]],

       [[85, 19, 19],
        [ 8, 12, 62],
        [16, 60, 31]],

       [[48, 50, 16],
        [68, 11, 34],
        [43, 72, 36]]])

- 58,63,48,16
- 94,76,12,62
- 85,19(last one), 48,16
- 46,22,43,36
- 66,76,46,22,8,63,16,31

In [127]:
# 8,\62
c[1,1,::2]

array([ 8, 62])

In [126]:
# 60
c[1,2,1] 


60

In [124]:
# 34
c[2,1,2]

34

In [123]:
#19 
c[1,0,2]

19

In [122]:
# 12
c[1,1,1]

12